services:

  c2:
    image: zheng-c2:latest
    privileged: true
    networks:
      internet:
        ipv4_address: 172.20.1.4
    ports:
      - "8080:8080"

  victim:
    image: zheng-victim:latest
    privileged: true
    environment:
      - MY_IP=172.20.0.2
      - MY_PORT=8080
      - PARENT_IP=172.20.1.4
      - PARENT_PORT=8080
      - C2_ADDR=172.20.1.4:8080
    networks:
      company:
        ipv4_address: 172.20.0.2
      internet:
        ipv4_address: 172.20.1.2

  host:
    image: zheng-host:latest
    privileged: true
    networks:
      company:
        ipv4_address: 172.20.0.3
      internet:
        ipv4_address: 172.20.1.3

networks:
  company:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  internet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24
